pipeline {
    agent any
    triggers {
        // Build every saturday morning
        cron('H 6 * * 6')
    }
    stages {
        stage ('Build Docker Images') {
            parallel {
                stage('xillio/jenkins') {
                    steps {
                        sh 'docker build --pull -t xillio/jenkins docker-jenkins'
                    }
                }
                stage('xillio/jenkins-agent') {
                    steps {
                        sh 'docker build --pull -t xillio/jenkins-agent docker-jenkins-agent'
                    }
                }
            }
        }
        stage ('Push Docker Image') {
            environment {
                DOCKER_CREDENTIALS = credentials('be60cbad-d54b-4f95-9f52-0a1615188699')
            }
            when {
                branch 'master'
            }
            steps {
                sh 'docker login --username "$DOCKER_CREDENTIALS_USR" --password "$DOCKER_CREDENTIALS_PSW"'
                sh 'docker push xillio/jenkins'
                sh 'docker push xillio/jenkins-agent'
            }
        }
    }
}
