pipeline {
    agent any
    triggers {
        // Build every saturday morning
        cron('H 6 * * 6')
    }
    stages {
        stage ('Build Docker Images') {
            steps {
                sh 'cd docker-jenkins && docker build --pull -t xillio/jenkins .'
                sh 'cd docker-jenkins-agent && docker build --pull -t xillio/jenkins-agent .'
            }
        }
        stage ('Push Docker Image') {
            environment {
                DOCKER_CREDENTIALS = credentials('be60cbad-d54b-4f95-9f52-0a1615188699')
            }
            when {
                branch 'master'
            }
            steps {
                sh 'docker login --username "$DOCKER_CREDENTIALS_USR" --password "$DOCKER_CREDENTIALS_PSW"'
                sh 'docker push xillio/jenkins'
                sh 'docker push xillio/jenkins-agent'
            }
        }
    }
}
